/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  IChemJson,
} from '@openchemistry/types';

declare global {

  namespace StencilComponents {
    interface OcMolecule {
      'cjson': IChemJson | string;
    }
  }

  interface HTMLOcMoleculeElement extends StencilComponents.OcMolecule, HTMLStencilElement {}

  var HTMLOcMoleculeElement: {
    prototype: HTMLOcMoleculeElement;
    new (): HTMLOcMoleculeElement;
  };
  interface HTMLElementTagNameMap {
    'oc-molecule': HTMLOcMoleculeElement;
  }
  interface ElementTagNameMap {
    'oc-molecule': HTMLOcMoleculeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'oc-molecule': JSXElements.OcMoleculeAttributes;
    }
  }
  namespace JSXElements {
    export interface OcMoleculeAttributes extends HTMLAttributes {
      'cjson'?: IChemJson | string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;